# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: FortifyDemo
  name: Default

steps:

- task: FedRampFortifyOnDemandStatic@8
  inputs:
    FortifyProjects: 'https://github.com/halehn32/IWA.git'
    BSIToken: 'eyJ0ZW5hbnRJZCI6MSwidGVuYW50Q29kZSI6IkRHUiIsInJlbGVhc2VJZCI6MTgyMDYsInBheWxvYWRUeXBlIjoiQU5BTFlTSVNfUEFZTE9BRCIsImFzc2Vzc21lbnRUeXBlSWQiOjI3LCJ0ZWNobm9sb2d5VHlwZSI6IkpBVkEvSjJFRS9Lb3RsaW4iLCJ0ZWNobm9sb2d5VHlwZUlkIjo3LCJ0ZWNobm9sb2d5VmVyc2lvbiI6IjEuOCIsInRlY2hub2xvZ3lWZXJzaW9uSWQiOjEyLCJhdWRpdFByZWZlcmVuY2UiOiJBdXRvbWF0ZWQiLCJhdWRpdFByZWZlcmVuY2VJZCI6MiwiaW5jbHVkZVRoaXJkUGFydHkiOmZhbHNlLCJpbmNsdWRlT3BlblNvdXJjZUFuYWx5c2lzIjp0cnVlLCJwb3J0YWxVcmkiOiJodHRwczovL2ZlZC5mb3J0aWZ5Z292LmNvbS8iLCJhcGlVcmkiOiJodHRwczovL2FwaS5mZWQuZm9ydGlmeWdvdi5jb20iLCJzY2FuUHJlZmVyZW5jZSI6IlN0YW5kYXJkIiwic2NhblByZWZlcmVuY2VJZCI6MX0='
    APIAuthenticationType: '2'
    Username: 'haleh_fed'
    PersonalAccessTokenSecret: 'dEEnY2U3U0h1MWljYjM0OFhocGZCQihad217R1pZ0'
    TenantID: 'DGR'
    EntitlementPreference: '1'
    PurchaseEntitlements: false
    PreferRemediation: false

- task: FortifyOnDemandDynamic@7
  inputs:
    APIUrl: 'https://api.ams.fortify.com'
    ReleaseId: '1262505'
    APIAuthenticationType: '2'
    Username: 'hnematollahy.fb24'
    PersonalAccessTokenSecret: 'ZjVcV2RjandZWkdtczdwbFNtWlZ7T1t2MnZiMDBJ0'
    TenantID: 'FranklinBank24'
    EntitlementPreference: '1'